"""Fill ms-poc .env from Azure CLI (run after az login)."""

from __future__ import annotations

import json
import subprocess
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
ENV_PATH = ROOT / ".env"

RG = "rg-ai-sales-poc"
OPENAI_ACCOUNT = "oai-ms-poc"
CHAT_DEPLOYMENT = "gpt-5-mini"
EMBEDDING_DEPLOYMENT = "text-embedding-3-small"
SEARCH_SERVICE = "search-ms-poc"
SEARCH_INDEX = "enterprise-knowledge"
STORAGE_ACCOUNT = "stmspoc85167153"


def az_json(args: list[str]) -> dict | list:
    result = subprocess.run(
        ["python", "-m", "azure.cli", *args, "-o", "json"],
        capture_output=True,
        text=True,
        check=True,
    )
    return json.loads(result.stdout)


def main() -> None:
    account = az_json(["cognitiveservices", "account", "show", "-g", RG, "-n", OPENAI_ACCOUNT])
    keys = az_json(["cognitiveservices", "account", "keys", "list", "-g", RG, "-n", OPENAI_ACCOUNT])
    search_keys = az_json(["search", "admin-key", "show", "--service-name", SEARCH_SERVICE, "-g", RG])
    storage_conn = subprocess.run(
        [
            "python",
            "-m",
            "azure.cli",
            "storage",
            "account",
            "show-connection-string",
            "-g",
            RG,
            "-n",
            STORAGE_ACCOUNT,
            "--query",
            "connectionString",
            "-o",
            "tsv",
        ],
        capture_output=True,
        text=True,
        check=True,
    ).stdout.strip()

    lines = {
        "AZURE_AI_ENDPOINT": account["properties"]["endpoint"],
        "AZURE_AI_API_KEY": keys["key1"],
        "AZURE_CHAT_DEPLOYMENT": CHAT_DEPLOYMENT,
        "AZURE_EMBEDDING_DEPLOYMENT": EMBEDDING_DEPLOYMENT,
        "AZURE_SEARCH_ENDPOINT": f"https://{SEARCH_SERVICE}.search.windows.net",
        "AZURE_SEARCH_INDEX": SEARCH_INDEX,
        "AZURE_SEARCH_API_KEY": search_keys["primaryKey"],
        "AZURE_STORAGE_ACCOUNT": STORAGE_ACCOUNT,
        "AZURE_STORAGE_CONNECTION_STRING": storage_conn,
        "MCP_SERVER_URL": "http://mcp-server:8001",
        "CRM_API_URL": "http://mock-crm:8101",
        "SALES_API_URL": "http://mock-sales:8102",
        "TICKETS_API_URL": "http://mock-tickets:8103",
        "CONTRACTS_API_URL": "http://mock-contracts:8104",
        "PRODUCTS_API_URL": "http://mock-products:8105",
        "CHUNK_SIZE": "800",
        "CHUNK_OVERLAP": "120",
        "API_HOST": "0.0.0.0",
        "API_PORT": "8000",
        "CORS_ORIGIN": "http://localhost:5200",
        "DEV_AUTH_ENABLED": "true",
    }

    content = "# Generated by scripts/azure_fill_env.py - DO NOT COMMIT\n"
    content += "\n".join(f"{k}={v}" for k, v in lines.items()) + "\n"
    ENV_PATH.write_text(content, encoding="utf-8")
    print(f"Updated {ENV_PATH}")


if __name__ == "__main__":
    main()
